-- MySQL Script generated by MySQL Workbench
-- Sat Mar 18 21:48:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema task_manager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema task_manager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `task_manager` DEFAULT CHARACTER SET utf8 ;
USE `task_manager` ;

-- -----------------------------------------------------
-- Table `task_manager`.`task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `task_manager`.`task` ;

CREATE TABLE IF NOT EXISTS `task_manager`.`task` (
  `task_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `due_date` DATE NOT NULL,
  `complete` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`task_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
